### ISSUE TITLE
Add organizer for ics

### ISSUE THREAD

**Issue by FrankOssie** [spatie/calendar-links#104]
## What do you want to achieve?
Is there a posibility to add the organizer method so the ics file contains the organizer option and with an email address?
Something like $link->organizer('Name','Email@email.com')

**Comment by lptn** [comment]
@FrankOssie 
ICS has a lot of features. What we should do with other generators like google, Yahoo?

**Comment by FrankOssie** [comment]
> Hey @FrankOssie
> ICS has a lot of features. What we should do with other generators like google, Yahoo?

Try to implement as much as possible?

**Comment by lptn** [comment]
@FrankOssie

Yes, but let's say we'll add 20 new public method `Link` class, only few of them will make effect to Google, Yahoo and other then ICS services. Should we make an API of Link class such complex without providing value to Google, Yahoo, Outlook generators?

**Comment by FrankOssie** [comment]
> @FrankOssie
> 
> Yes, but let's say we'll add 20 new public method `Link` class, only few of them will make effect to Google, Yahoo and other then ICS services. Should we make an API of Link class such complex without providing value to Google, Yahoo, Outlook generators?

That's a good idea, let me know how i can help
