### ISSUE TITLE
Spaces replaced by "+" on Outlook.com

### ISSUE THREAD

**Issue by pcboii** [spatie/calendar-links#109]
## Context

1. PHP Version: 7.4.2
1. Package version: 1.4.2

## Describe the Bug

- Created a link.
- Clicked on the generated Outlook Web link.
- Noticed spaces in event title/description are replaced by "+".

Link Generated:
https://outlook.live.com/calendar/deeplink/compose?path=/calendar/action/compose&rru=addevent&startdt=2020-11-06T17:00:00Z&enddt=2020-11-06T18:00:00Z&subject=Appointment+with+Demo&body=Case+Number%3A+ABC-123

![2020-11-07_19-12-04](https://user-images.githubusercontent.com/74124548/98456052-7976b600-212d-11eb-9279-52911071e977.png)

## Expected Behavior

Display a space rather than "+".

**Comment by glitcha** [comment]
Having this problem too

**Comment by glitcha** [comment]
I have had a lot better results by doing a str_replace on the resulting link to remove the following path=/calendar/action/compose&rru=addevent

Spaces as expected now.

**Comment by lptn** [comment]
fixed within latest release, thanks to @iosley
