### ISSUE TITLE
$link->ics() not working correctly on Outlook mails

### ISSUE THREAD

**Issue by chavab1** [spatie/calendar-links#110]
## Context

1. PHP Version: 7.2
1. Package version: 1.4.2

## Describe the Bug

I followed the instructions and the links get generated correctly. I'm including the links in emails. When the email is received in Microsoft Outlook 2016 all of the links work as expected. However, when I try to open the link generated by $link->ics() I am prompted to dowload an app from the Microsoft Store. When I click on the link on a different email client, like Gmail, it opens correctly.

## Expected Behavior

I want the link to open the Calendar prompt like it does when I click on the link from an email opened in Gmail or Yahoo mail

**Comment by lptn** [comment]
@chavab1 
For ICS generator we use `data:text/calendar` link type. You can do some experiments by extending Ics generator and overriding `\Spatie\CalendarLinks\Generators\Ics::buildLink()`:
```php
$link->formatWith(new \Your\Custom\IcsGenerator());
```

and then share results with the community 💪
