### ISSUE TITLE
AllDay method does not work

### ISSUE THREAD

**Issue by alexv96** [spatie/calendar-links#111]
I am generating a link and when I put allDay(true) the link generates an error or I do not check the box all day in Gmail.

```
$link = Link::create($opportunity->name, $from,$to)
                ->allDay(true)
                ->description($activity->description);
```

**Comment by lptn** [comment]
@alexv96 
>he link generates an error

What sort of error? Can you please share the result code?

**Comment by lptn** [comment]
inactive, closing
