### ISSUE TITLE
outlook.com link not working as intended

### ISSUE THREAD

**Issue by odedta** [spatie/calendar-links#113]
## Context

1. PHP Version: 7.4
1. Package version: 1.4.2

## Describe the Bug
I'm using the code provided in the example to create 4 links to the different calendars, when I click on the outlook.com link the time in the link is not correct.

Steps to reproduce:
```
$event_title = 'test';
$next_date_start = date( 'Y-m-d H:i', strtotime( $next_date . ' ' . $next_time_start ) );
$next_date_end   = date( 'Y-m-d H:i', strtotime( $next_date . ' ' . $next_time_end ) );
$from            = DateTime::createFromFormat( 'Y-m-d H:i', $next_date_start );
$to              = DateTime::createFromFormat( 'Y-m-d H:i', $next_date_end );
$link            = Link::create( $event_title, $from, $to );
```

The data:
```
$next_date: string(10) "03/17/2021"
$next_time_start: string(5) "10:00"
$next_time_end: string(5) "11:00"
```

The output for `$link->webOutlook()` is this:
https://outlook.live.com/calendar/0/deeplink/compose?path=/calendar/action/compose&startdt=2021-03-17T10:00:00Z&enddt=2021-03-17T11:00:00Z&subject=test

When I click on the link I see 7am to 8am
![Screenshot_1](https://user-images.githubusercontent.com/13570550/105637245-17774400-5e32-11eb-9fa1-05496b711a32.jpg)

## Expected Behavior
Should see 10am to 11am

https://outlook.live.com/calendar/0/deeplink/compose?path=%2fcalendar%2faction%2fcompose&startdt=2021-03-17T10:00:00Z&enddt=2021-03-17T11:00:00Z&subject=%D7%A9%D7%A4%D7%AA+%D7%94%D7%9C%D7%91%D7%95%D7%A9+%D7%91%D7%A7%D7%A8%D7%91+%D7%99%D7%94%D7%95%D7%93%D7%99%D7%95%D7%AA+%D7%91%D7%90%D7%A8%D7%A6%D7%95%D7%AA+%D7%94%D7%90%D7%A1%D7%9C%D7%90%D7%9D

**Comment by Banquo1** [comment]
Didn't wor for me either. I replaced the base URL with outlook.office365.com and it worked for me (but the titel and body text ist encoded wrong):
// .... generate the $link Object... then:
$weboutlook = str_replace('https://outlook.live.com','https://outlook.office365.com',$link->webOutlook());

**Comment by odedta** [comment]
Hello,
When I used your code I was redirected to outlook.office365.com, however, when I tried to login with my account I saw this message:
"You can't sign in here with a personal account. Use your work or school account instead." - That's probably because my account is from old Hotmail from like 20 years ago :-P

I don't know if your solution helps me or not but thanks anyway!
