### ISSUE TITLE
Accented characters lost in Outlook 

### ISSUE THREAD

**Issue by Naghal** [spatie/calendar-links#117]
## Context

1. PHP Version: 7.4.3
1. Package version: 1.4.3

## Describe the Bug
When opening a calendar link with Outlook 2016, the accented characters are lost. It works fine with the online version of outlook.

1. Add accented character to the detail section of the link.
2. Generate the link
3. Open it in outlook 2016
4. The accented characters are not present in the description

## Expected Behavior
The accented characters are present just like in the web version.

The accented characters are present just like in the web version.

Example:
![2021-03-26](https://user-images.githubusercontent.com/29404633/112676886-672cb880-8e3f-11eb-9f7e-1a95d7366e97.png)
![image (1)](https://user-images.githubusercontent.com/29404633/112676957-7f9cd300-8e3f-11eb-98c0-9c4becb7223b.png)

**Comment by dravenk** [comment]
@Naghal Hi. It's maybe fixed by this PR. Could you give it a try and give some feedback? Thank you.
https://github.com/spatie/calendar-links/pull/150
