### ISSUE TITLE
Class not found

### ISSUE THREAD

**Issue by dyned-devan** [spatie/calendar-links#118]
## Context

1. PHP Version: 7.0.30
1. Package version: 1.3.0

## Describe the Bug

So I already put use Spatie\CalendarLinks\Link after require_once 'vendor/autoload.php' at the top of the page but still come up error class not found, im using composer to install the spatie/calendar-links version 1.3.0 because i use php 7.0.30, package was success to install and already generate the autoload files

## Expected Behavior

no error class not found

**Comment by lptn** [comment]
`\Spatie\CalendarLinks\Link` is a valid FQCN, the issue it not related to this repository (most likely composer setup problem, need to re-run composer auto dump or fix a way on how to include composer’s autoload.php)

**Comment by dyned-devan** [comment]
Hey thanks for the reply, I think no issue on the composer because I installed other package and works just fine. I already remove the vendor and do composer install & dump-autoload again but still have the same issue. It works on my localhost just fine with the precisely same code, same package (spatie 1.3.0), same php version also
