### ISSUE TITLE
Trouble with Daylight Savings Time

### ISSUE THREAD

**Issue by ghost** [spatie/calendar-links#119]
## Context

1. PHP Version: 7.4.11
1. Package version: 1.4.3

## Describe the Bug

An event's calendar links work correctly using the google() method, but the ics() method for Outlook leads to times that are one-hour off. I believe this has to do with Daylight Savings Time. Here is the code used to create the links:

```php
$from = \DateTime::createFromFormat('Y-m-d H:i:s', '2021-05-19 17:30:00')->setTimezone(new \DateTimeZone('America/New_York'));
$to = \DateTime::createFromFormat('Y-m-d H:i:s', '2021-05-19 19:00:00')->setTimezone(new \DateTimeZone('America/New_York'));

$link = Link::create('Event', $from, $to);

return $link;
```

In Google, the event shows correctly as 5:30 to 7:00 PM. In Outlook, the event runs from 6:30 to 8:00 PM.

## Expected Behavior

I'd expect the event to show the correct time of 5:30 to 7:00 PM in Outlook, too.

**Comment by mattpaz** [comment]
Possibly related:
https://github.com/spatie/calendar-links/issues/73
