### ISSUE TITLE
ical not working on MacOS

### ISSUE THREAD

**Issue by woutmeijer** [spatie/calendar-links#129]
Version Details:
Spatie Verion = 1.6
Laravel Version = 8.0

Currently when I generate an ical file it doesn't add it to the apple calander. 

When I was debugging the issue I found out this happened because the file doesn't include this line that's generated when  creating a ical file from an Icalendar item: `DTSTART;TZID=Europe/Amsterdam:20210622T160000`

Is there a way we could generate this line from inside the package?

**Comment by MichielBier** [comment]
After reviewing with woutmeijer we found out that if you feed a Carbon instance to this lib, the ICS function will not always work as expected because of the way the format->() function is handled. In certain cases we got 
```
+01:00:20220110T152742 out of format->('e:Ymd\THis');

instead of the expected:
Europe/Amsterdam:20220110T152742⏎
```

**Comment by mashehu** [comment]
This is still an issue, tested with v1.8 and php 7.4

**Comment by lptn** [comment]
Hey @MichielBier 

Can you please provide code snippet to reproduce it?
