### ISSUE TITLE
Support Carbon Library

### ISSUE THREAD

**Issue by espradley** [spatie/calendar-links#138]
## What do you want to achieve?
Support for Carbon dates.

For example:

```php
public function generateCalendarLink(){

        $startDate = new Carbon($this->start_date);

        if(!$endDate = $this->end_date){
            $endDate = $startDate->addHours(1);
        }

        $from = $startDate->format('Y-m-d H:i');
        $to = $endDate->format('Y-m-d H:i');


        $link = Link::create($this->name, $from, $to)
            ->description($this->description)
            ->address($this->location);

        return $link;
    }

```

Please check [Package principles](https://github.com/spatie/calendar-links#package-principles) before you create a request.

**Comment by lptn** [comment]
the package uses `DateTimeInterface` means it also supports `Carbon`. 

@espradley Do you have any issues on using Carbon and this package?

**Comment by jigarhalani** [comment]
Yes, carbon is not working
