### ISSUE TITLE
"All day" events support

### ISSUE THREAD

**Issue by andrewmarino** [spatie/calendar-links#15]
This works great for calendar links with start time and end times but I found calendar links without start or end times ("all day events") it will still use a timestamp.

- - -

Example:
```php
$from = DateTime::createFromFormat('Ymd', '20180604');
```

Changing `$link->from->format('Ymd\THis')` to `$link->from->format('Ymd')` in the Generator files works but I'd like to avoid overriding files directly. Maybe we can set this through `$link::create` as optional? 

```php
$link = Link::create('Title', $from, $to)
  ->allDay(true)
  ->description('Description')
  ->address('Address')
```

**Comment by lptn** [comment]
@andrewmarino 
this issue is fixed https://github.com/Eyalevin/calendar-links/commit/2ce22ceca1f166d01af1e274246e784f9d742009 and fix is merged: see `All day event` #19
