### ISSUE TITLE
allDay Method not working

### ISSUE THREAD

**Issue by PSchmitz90** [spatie/calendar-links#151]
## Context

1. PHP Version: 7.4.25
1. Package version: 1.7.1

## Describe the Bug

Added ->allDay() in Creation of Link

```
$link = Link::create($event->title, $from, $to)
            ->description($description)
            ->allDay(true)
            ->address($address);
```

Getting Error-Message: "Call to undefined method Spatie\CalendarLinks\Link::allDay()"

**Comment by lptn** [comment]
Hey @PSchmitz90 
There is no such method `allDay()`, the only way to set it - use `Link::createAllDay` or  `Link::create()` with true as 4th argument
