### ISSUE TITLE
Add support for DESCRIPTION in ICS output

### ISSUE THREAD

**Issue by cdubz** [spatie/calendar-links#157]
## What do you want to achieve?

#136 replaced the ICS `DESCRIPTION` with `X-ALT-DESC` which is only supported by Microsoft products. This value does not get imported by other calendars (e.g., the Calendar app on macOS).

I think it would be ideal if `DESCRIPTION` could be re-added and potentially forced to plaintext. From a quick manual test it appears that having both `DESCRIPTION` and `X-ALT-DESC` is fine -- in that case Calendar.app uses `DESCRIPTION` and Outlook uses `X-ALT-DESC`.

**Comment by lptn** [comment]
hey @cdubz 
Agree! The simpler - the better. Can you please help us with a PR? This is a hacktoberfest BTW :)
