### ISSUE TITLE
Unable to open file for reading

### ISSUE THREAD

**Issue by LakshanMendis** [spatie/calendar-links#162]
## Context

1. PHP Version: 

## Describe the Bug

Unable to open file for reading [data:text/calendar;charset=utf8;base64,QkVHSU46VkNBTEVOREFSDQpWRVJTSU9OOjIuMA0KUFJPRElEOlNwYXRpZSBjYWxlbmRhci1saW5rcw0KQkVHSU46VkVWRU5UDQpVSUQ6OGI4YmU1MTEyMWZhN2VkNDBjZjUyYjI3MDdiMDQ4ZjgNClNVTU1BUlk6TWVldGluZw0KRFRTVEFNUDtUWklEPUFzaWEvQ29sb21ibzoyMDIyMTIzMVQwOTAwMDANCkRUU1RBUlQ7VFpJRD1Bc2lhL0NvbG9tYm86MjAyMjEyMzFUMDkwMDAwDQpEVEVORDtUWklEPUFzaWEvQ29sb21ibzoyMDIyMTIzMVQxMDAwMDANClgtQUxULURFU0M7Rk1UVFlQRT10ZXh0L2h0bWw6TWluZGhlYWxzDQpMT0NBVElPTjpNaW5kaGVhbHMNCkVORDpWRVZFTlQNCkVORDpWQ0FMRU5EQVI=]

**Comment by lptn** [comment]
@LakshanMendis 
sorry, maintainers can't spend their time without a knowledge about the package version (probably it's already solve). Your PR is welcome.
