### ISSUE TITLE
Option to set Reminder section

### ISSUE THREAD

**Issue by AlexeyUna** [spatie/calendar-links#165]
There is no possibility to add reminder for event. View details here [Alarm Component](https://icalendar.org/iCalendar-RFC-5545/3-6-6-alarm-component.html)

**Comment by lptn** [comment]
@AlexeyUna 
what's about [other services](https://github.com/spatie/calendar-links#package-principles), should they just ignore this feature?

**Comment by AlexeyUna** [comment]
> 

Well, may be the best solution is just to add method which allows to add own/any section to output (not only Alarm or any other)
