### ISSUE TITLE
$link->ics() not working as specified

### ISSUE THREAD

**Issue by jahid56** [spatie/calendar-links#17]
I have just installed calendar-links package. This wirks perfectly fine for  $link->google() and $link->yahoo()  as it generate link. But when I used $link->ics() it does not generate any link. I did not find out where the problem is.

**Comment by savager** [comment]
you'll need to make it a downloadable link

**Comment by jahid56** [comment]
@savager  So how can make a downloadable link? In the documentation its only told taht to add ics only $link->ics() supposed to be work. Will you please give an example?

**Comment by sebastiandedeyne** [comment]
Please provide snippets including as much code as possible. I can't look into this without seeing what's going wrong.

- How are you creating your `Link` instance?
- Your view
- Your view's html output

**Comment by savager** [comment]
Well I believe the issue is do to how chrome handles file downloads and or partial downloads. I'm generating my event like so:

$link = Link::create('test', $from, $to)
				->description('test')
				->address('test');

`<a download="event.ics" href="' . $link->ics() . '">Apple Calendar</a>`

which outputs:

`<a download="event.ics" href="application/octet-stream;charset=utf8,%0ABEGIN:VCALENDAR%0AVERSION:2.0%0ABEGIN:VEVENT%0ADTSTART:20180601T180000%0ADTEND:20180601T210000%0ASUMMARY:test%0ADESCRIPTION:test &#10;%0ALOCATION:test%0AEND:VEVENT%0AEND:VCALENDAR">Apple Calendar</a>`

which results in the latest chrome saying file not found

**Comment by savager** [comment]
just as a follow up, I started changing the ICS generator believing it was the formatting of the generated ICS file, but the issue actually seems to be with chrome. so i decided i didn't have time to mess with it and just searched for a dumb JS download script. Although you may want to add a uid to the ICS: 'UID:' . md5($link->title ? $link->title : "")

@jahid56 I used the following format:

```return array(
				'#markup' => '<a target="_blank" href="' . $link->google() . '">Google</a><br/>' .
				'<a target="_blank" href="' . $link->yahoo() . '">Yahoo</a><br/>' .
				'<a class="apple-calendar" data-href="' . $link->ics() . '">Apple Calendar</a>',
			);```

and then used the following JS that i found on some codepen. tested and it seems to work on all major browsers:

```
const downloadFile = function(sUrl) {
  //iOS devices do not support downloading. We have to inform user about this.
  if (/(iP)/g.test(navigator.userAgent)) {
    //alert('Your device does not support files downloading. Please try again in desktop browser.');
    window.open(sUrl, '_blank')
    return false
  }

  //If in Chrome or Safari - download via virtual link click
  if (isChrome || isSafari) {
    //Creating new link node.
    var link = document.createElement('a')
    link.href = sUrl
    link.setAttribute('target', '_blank')

    if (link.download !== undefined) {
      //Set HTML5 download attribute. This will prevent file from opening if supported.
      var fileName = sUrl.substring(sUrl.lastIndexOf('/') + 1, sUrl.length)
      link.download = fileName
    }

    //Dispatching click event.
    if (document.createEvent) {
      var e = document.createEvent('MouseEvents')
      e.initEvent('click', true, true)
      link.dispatchEvent(e)
      return true
    }
  }

  // Force file download (whether supported by server).
  if (sUrl.indexOf('?') === -1) {
    sUrl += '?download'
  }

  window.open(sUrl, '_blank')
  return true
}

const isChrome = navigator.userAgent.toLowerCase().indexOf('chrome') > -1
const isSafari = navigator.userAgent.toLowerCase().indexOf('safari') > -1

$('.apple-calendar').on('click', e => {
  downloadFile($(e.target).data('href'))
  return false
})


```

**Comment by jahid56** [comment]
@sebastiandedeyne  Here I attcahed the screenshot of the creating your Link instance, View and View Output. Please take a look
![create link instance](https://user-images.githubusercontent.com/18249715/41214632-240d21ec-6d6e-11e8-87b4-b62b7b145b69.png)
![view image](https://user-images.githubusercontent.com/18249715/41214633-245bcbe4-6d6e-11e8-8dc9-34dbed0d5de8.png)
![view](https://user-images.githubusercontent.com/18249715/41214634-24a0ade0-6d6e-11e8-8d1a-b62cda3e021e.png)

**Comment by jflores-e3** [comment]
For anyone who comes across this issue because they are having issues with the `->ics()` function and creating a file/text stream - the Link response encodes newlines as `'%0d%0a'` and adds `'data:text/calendar;charset=utf8,` at the beginning of the string - these both cause problems if dumped into a file output and will cause the ICS to be invalid. Replacing `'%0d%0a'` with `PHP_EOL` and `'data:text/calendar;charset=utf8,` with an empty string before you output the link to your file stream will allow it to validate properly

**Comment by lptn** [comment]
Hey @jflores-e3 
Could please provide more details about the problem you faced?

What is the package version you use?

Let me share my example.

I use the latest version ([1.2.2](https://github.com/spatie/calendar-links/releases/tag/1.2.2)) of this package on a one of our products. Here you can find an example of usage (check for `Add to my calendar` button): https://www.interaction-design.org/events/external-ux-events/fitc-amsterdam-2019-feb-18th-2019

and here is an output:
```html
<a href="data:text/calendar;charset=utf8,BEGIN:VCALENDAR%0d%0aVERSION:2.0%0d%0aBEGIN:VEVENT%0d%0aUID:f5cb01a8b38671117576010816d6e1fe%0d%0aSUMMARY:FITC Amsterdam 2019%0d%0aDTSTART;TZID=Europe/Amsterdam:20190218T090000%0d%0aDTEND;TZID=Europe/Amsterdam:20190219T180000%0d%0aDESCRIPTION:Now in its 12th year\, FITC returns to Amsterdam to host their groundbreaking design and tech event on the future of innovation\, design and all the cool shit in between.%0d%0aLOCATION:Pakhuis de Zwijger\, Piet Heinkade 179\, Amsterdam\, Netherlands%0d%0aEND:VEVENT%0d%0aEND:VCALENDAR" download="FITC Amsterdam 2019.ics" target="_blank" class="button button--secondary" role="button">iCalendar / Outlook</a>
```

I didn't experienced any problems with downloading ics file. I also checked downloaded file using special [validator](http://ical-validator.herokuapp.com) and didn't find any major problems:

![image](https://user-images.githubusercontent.com/5278175/52009920-221dcd80-24e5-11e9-9d38-6c07e8401bda.png)

**Comment by lptn** [comment]
@jflores-e3 
I got it! Yes, this package was created to create links, not files. I we can create a new generator for ics files, but it's not a direct purpose of this package: there are a lot of other package that can create ics files. So, I don't think we need to implement it (even package name contains `Link` word)

**Comment by mgarcia96** [comment]
> @jflores-e3
> I got it! Yes, this package was created to create links, not files. I we can create a new generator for ics files, but it's not a direct purpose of this package: there are a lot of other package that can create ics files. So, I don't think we need to implement it (even package name contains `Link` word)
> 
> Anyway, thanks a lot for your clarification 👍

Hey @lptn thanks to your response, I was trying to download the file unsuccessfully.
Guys, **if you are trying to download** the file **this package is only for generate links**, if you want to download ICS files I use this package:

[https://github.com/markuspoerschke/iCal](https://github.com/markuspoerschke/iCal)
