### ISSUE TITLE
Start Time is not accurate in Outlook on mobile screen sizes

### ISSUE THREAD

**Issue by nebulousGirl** [spatie/calendar-links#172]
## Context

1. PHP Version: 8.2
1. Package version: 1.8.0

## Describe the Bug

Generate a link for Web Outlook. Click the link using your phone. The start time will be the next hour from current time and not the expected start time.

## Expected Behavior

The event with the start time set in the URL.

This seems to be a general issue with Microsoft Outlook and not related to the library, but I'm hoping we could find an alternate way to provide accurate links for Outlook when used on a phone.

**Comment by lptn** [comment]
@nebulousGirl 

Unfortunately, such issues of the scope of this package, at least till calendar services provide docs. You can try your luck at the https://github.com/InteractionDesignFoundation/add-event-to-calendar-docs repo (create a discussion, probably someone will find an answer in JS code served by outlook
