### ISSUE TITLE
ICS description doesn't show

### ISSUE THREAD

**Issue by RyanSacks** [spatie/calendar-links#173]
## Context

1. PHP Version: 7.4.29
1. Package version: * 1.8.0

## Describe the Bug
When I download the .ics file, everything works except for the description. After importing the .ics file into my iCal, everything shows the way I want except the Description area is blank. I want to add a URL of the event so they can click and be redirected to it. Not even plain text is showing.

1. Create the following code, replacing all of the variables inside the ::create method with valid data.
```php
$url = "<a href='https://google.com'>My Event</a>";
$link = Link::create($eventName, $startDate, $endDate)
            ->description($url)
            ->address("1234 Fake Street");
            
echo $link->ics();
```

2. Copy the echo url in a Chrome browser tab (Version 112.0.5615.49 (Official Build) (x86_64)), a file should be downloaded.
3. Import that .ics file inside your iCal. I have a Macbook Pro, Mac OS Mojave, Version: 10.14.6

## Expected Behavior

1. I've copy/pasted 2 screenshots. 1 of the bug and 1 of the expected result. Where it says Add "Notes/Add URL" that's where I want to add a link. My OS is a bit old, maybe that's the issue? Anyway, please see below.

![bug](https://user-images.githubusercontent.com/48108073/232143385-baabcb05-59ae-4dfe-bccc-ad3748d53ab5.png)
![expected_result](https://user-images.githubusercontent.com/48108073/232143502-06c3bae3-a670-48de-85ea-a9976cf9a21a.png)

**Comment by lptn** [comment]
Hi @RyanSacks 
In [1.8.2](https://github.com/spatie/calendar-links/releases/tag/1.8.2) version we have changed implementation. Which one exactly version do you use?

**Comment by RyanSacks** [comment]
I'm using 1.8.0
So if I update the package it should work correctly?

**Comment by lptn** [comment]
@RyanSacks 
probably yes, it depends on implementation of your calendar software. If you don't want to update all composer packages, you can update only this one: `composer update spatie/calendar-links`

**Comment by RyanSacks** [comment]
@lptn 
I updated the package, but it didn't solve the issue.

**Comment by RyanSacks** [comment]
@lptn 
Hi Alies,
Anything else I can try?

**Comment by lptn** [comment]
Hi Ryan!

I just checked on 18.5 - it works with macOS calendar on my end. Most likely you use 1.8.0 that has an experimental change made within https://github.com/spatie/calendar-links/pull/136 and simply doesn't work with macOS calendar. Most likely all you need - just to update the package

**Comment by RyanSacks** [comment]
@lptn 
Hi Alies,
I updated the package using the command you gave me, but when I run this command:
`composer show spatie/calendar-links | grep 'versions'`
It still says version: * 1.8.0
Any idea why it doesn't say 1.8.5 ?

**Comment by lptn** [comment]
@RyanSacks 
I just checked changelogs, in 1.8.1  we have dropped PHP 7.4 support. Options you have:
a) upgrade PHP version to 8.0+
b) lock do not use 1.8.0  package version (e.g. use "spatie/calendar-links: "1.7.2 || ^1.8.1")

**Comment by RyanSacks** [comment]
@lptn 

I'll discuss with my team if we have the time to upgrade to php 8.0+.
Otherwise forgive me. When you say "lock do not use 1.8.0 package version"...
You mean change the package version in the composer.lock file?

**Comment by lptn** [comment]
I'm sorry, I don't provide individual advice service on composer and PHP here, I'm just a contributor here.

But let me to share the final advice: in composer.json use "spatie/calendar-links: "1.7.2 || ^1.8.1" and then update dependencies or just a single dependency (`composer update` or `composer update spatie/calendar-links` -- this should change the package version to 1.7.2 [without this bug] and make your composer ready for further package updates when you upgrade you PHP version)

**Comment by RyanSacks** [comment]
@lptn
Thank you so much!!!
