### ISSUE TITLE
Authorization: cannot create pull request

### ISSUE THREAD

**Issue by S-Braeutigam** [spatie/calendar-links#176]
## Context

We would like to create a pull request for the feature of ICS alarm/reminder functionality.

## Describe the Bug

When trying to create a pull request for this project, we get the following exception: 
"Can't create a new pull request: Push failed: remote: Permission to spatie/calendar-links.git denied to S-Braeutigam. unable to access 'https://github.com/spatie/calendar-links.git/': The requested URL returned error: 403"

**Comment by lptn** [comment]
pls try `https://github.com/spatie/calendar-links.git` (without tailing `/`). Also, you firstly need to make a fork, I would recommend you to use GitHub UI for that. If you need any help on this, https://github.com/firstcontributions/first-contributions is a good starting point
