### ISSUE TITLE
ICS file not showing rsvp in outlook

### ISSUE THREAD

**Issue by jigarhalani** [spatie/calendar-links#181]
## Context

1. PHP Version: PHP 8.1.12
1. Package version: 1.8.5

## Describe the Bug
1) Generate ics using calendar-link package
2) attach in email using laravel mailable
3) send to any outlook email.

```php
$link = Link::create($this->appointment->subject, $this->appointment->expected_start_time, $this->appointment->expected_end_time);
            if($this->appointment->comment){
                $link->description($this->appointment->comment);
            }
            
$markdown->attach($link->ics(), ['as' => 'meeting.ics', 'mime' => 'text/calendar']);
```

for more you guys can visit my [stack question link](https://stackoverflow.com/questions/77861805/outlook-not-showing-rsvp-button-not-able-to-parse-ics-file-when-it-sent-from-l)
`

## Expected Behavior
Should show RSVP button or Appointment description in email itself.
[
<img width="644" alt="accepted behaviour" src="https://github.com/spatie/calendar-links/assets/15965253/99d09ecd-4384-4554-a7b2-74892b6cac2f">
](url)

**Comment by atymic** [comment]
Can you try this with the new file const?
https://github.com/spatie/calendar-links/pull/185
