### ISSUE TITLE
All Day Event Issues - Continued

### ISSUE THREAD

**Issue by atymic** [spatie/calendar-links#183]
See https://github.com/spatie/calendar-links/issues/175 for background.

There's quite a few issues with this package, detailed below.
I'm considering doing a re-write of the all day feature, to make that generation logic separate.

## Time zone issues
If creating all day events via `::createAllDay`, and the timezone is not UTC, the dates on the event are wrong, because timezone is irrelevant for all day events. This happens for all providers.
```
return Link::createAllDay(
            'All day bugs',
            $dateTimeClass::createFromFormat('Y-m-d', '2024-01-25', new DateTimeZone('Pacific/Wake'))->setTime(0,0),
            5
        )->description($description); 
```

Produces link starting on the 24, due to the unintended timezone conversion. Ignore the end date being wrong also (different issue).
```
https://calendar.google.com/calendar/render?action=TEMPLATE&dates=20240124/20240129&ctz=Pacific/Wake&text=ALl+day+bugs&details=Testing+all+day
```

On cal:

![Screen Shot 2024-01-26 at 08 49 44@2x](https://github.com/spatie/calendar-links/assets/50683531/6bee4d3d-c766-4163-88ea-ec3e973df9b0)

## Google provider end date issue
Google expects the next whole day as the end date in the URL for all day events. Ie, to create an event from `2024-01-25` - `2024-01-30`, `dates=20240125/20240131` should be passed.

As per the ICS spec, this is a 5 day event, but passing the start date with 5 day duration causes you to end up with a event ending on the 29th.

## Other issues
Office provider also seems wrong. Will update issue once I have debugged all cases

**Comment by atymic** [comment]
@freekmurze would you consider accepting me as a maintainer of this package? There are issues/prs open for a long time. Happy to have you/anyone else also review all PRs/changes before merging.

**Comment by alies-dev** [comment]
should be fixed by https://github.com/spatie/calendar-links/releases/tag/1.8.6
