### ISSUE TITLE
How does this package compare to spatie/icalendar-generator

### ISSUE THREAD

**Issue by hichemfantar** [spatie/calendar-links#196]
I noticed there are 2 packages that create ics calendars.
How does calendar-links compare to [icalendar-generator](https://github.com/spatie/icalendar-generator)

**Comment by alies-dev** [comment]
this one has a focus to support different services, not only ics format. And supports only basic ics features. If you need ics only - it's better to use [icalendar-generator](https://github.com/spatie/icalendar-generator)
