### ISSUE TITLE
Class Link not found

### ISSUE THREAD

**Issue by renzramos** [spatie/calendar-links#20]
Fatal error: Uncaught Error: Class 'Link' not found in C:\xampp\htdocs\test\add-calendar\xxx.php:9 Stack trace: #0 {main} thrown in C:\xampp\htdocs\test\add-calendar\xxx.php on line 9

**Comment by Eyalevin** [comment]
Did you add 
`use Spatie\CalendarLinks\Link;`
at the top of the file?
