### ISSUE TITLE
Ability to specify timezone

### ISSUE THREAD

**Issue by greenacorn-michael** [spatie/calendar-links#23]
I'm having issues with events stored in UTC displaying in the wrong timezone on Google Calendar. I believe the correct format string should be `Ymd\THis\Z`. The `Z` indicates the the time is already in UTC, and it will be converted by Google Calendar to the user's local timezone. I assume the same issue exists for ICS and Yahoo.

**Comment by freekmurze** [comment]
Feel free to PR a fix for this!

**Comment by DenzoNL** [comment]
@freekmurze Would you be so kind to review and merge this? :) Was working on my own PR for this until I saw this issue/PR, but I'd rather see this get merged instead :)

Thanks in advance!

**Comment by lptn** [comment]
I've just release timezone support as a part of 1.1.2 version

**Comment by freekmurze** [comment]
Thanks @lptn 👍
