### ISSUE TITLE
Create multiple events

### ISSUE THREAD

**Issue by vhs1092** [spatie/calendar-links#26]
Hi, I am using your package but I am not able to create more than one event for the $link->ics(), how can I achieve that?

**Comment by Eyalevin** [comment]
I am very sorry I am not understanding the question did you want  make multiple links ? Or one link make multiple events?

**Comment by vhs1092** [comment]
yes I needed one link make multiple events, I  made it work like this:

`$ical = 'BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
METHOD:PUBLISH
X-WR-TIMEZONE:America/New_York
BEGIN:VTIMEZONE
TZID:America/New_York
X-LIC-LOCATION:America/New_York
BEGIN:STANDARD
TZOFFSETFROM:-0400
TZOFFSETTO:-0500
TZNAME:EST
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:20180311T020000
TZOFFSETFROM:-0500
TZOFFSETTO:-0400
RDATE:20190310T020000
TZNAME:EDT
END:DAYLIGHT
END:VTIMEZONE' . chr(10);

       
        foreach ($data as $key => $value) {
            $types = array_column($this->types, 'name');
            $type = $types[$value->type + 1];
            //* Adding events
            $ical .= 'BEGIN:VEVENT' . chr(10);
            $ical .= 'UID:adasdadasd' . $key . chr(10);
            $ical .= 'CATEGORIES;LANGUAGE=en-US:'. $type . chr(10);
            $ical .= 'DTSTART;TZID=America/New_York:'.Carbon::createFromFormat('Y-m-d H:i:s', $value->start_date)->format('Ymd\THis') . chr(10);
            $ical .= 'DTEND;TZID=America/New_York:'.Carbon::createFromFormat('Y-m-d H:i:s', $value->end_date)->format('Ymd\THis') . chr(10);
            $ical .= 'SUMMARY:'.$value->user->name . chr(10);
            $ical .= 'DESCRIPTION:'.addcslashes($value->description, "\n"). chr(10);
            $ical .= 'END:VEVENT' . chr(10);

        }

$ical .= 'END:VCALENDAR';
        //*End calendar
        $file = fopen("events.ics", "w+");
        fwrite($file, $ical);
        fclose($file);`

**Comment by Bedo-christian** [comment]
hi vhs1092,
Do you resolved this?

**Comment by nafil-gigsboard** [comment]
Reference This article for setting multiple or recurring event generation for google calendar
https://medium.com/collaborne-engineering/google-calendar-links-4fa1b6c01c7c

for ics refer this article
https://stackoverflow.com/questions/1823647/grouping-multiple-events-in-a-single-ics-file-icalendar-stream

**Comment by betweenbrain** [comment]
Does this library support multiple occurrence events, as described above?

**Comment by bastien70** [comment]
Up, is it possible to create a link which will add multiple events at the same time ?

**Comment by lptn** [comment]
@bastien70 
no
