### ISSUE TITLE
Yahoo Generator broken

### ISSUE THREAD

**Issue by Robert-Hucks** [spatie/calendar-links#35]
```
Call to a member function format() on string.
```

Throws this error on [line 15 of src/Generators/Yahoo.php](https://github.com/spatie/calendar-links/blob/be65b582bc34bdd2c57231c6de50ac085724f606/src/Generators/Yahoo.php#L15).

I think the problem is that in the recent update for this file the `$from` and `$to` attributes are being used as `DateTime` objects when they are actually stored as [strings in the constructor](https://github.com/spatie/calendar-links/blob/be65b582bc34bdd2c57231c6de50ac085724f606/src/Link.php#L47) and used as such in the other Generator files.

I imagine a simple fix for this would be to store them as their `DateTime` objects and then update the generator files to format their strings as required, or maybe do the reverse and create a new `DateTime` object in Yahoo.php specifically to reformat the string and get the time difference.

Hopefully I haven't missed anything.

**Comment by indpurvesh** [comment]
I had the same issue too.

**Comment by freekmurze** [comment]
We'll handle this further in #40
