### ISSUE TITLE
ICS LOCATION should allow commas

### ISSUE THREAD

**Issue by aethr** [spatie/calendar-links#36]
Hi there,

I'm working on a project that uses your Link formatter to generate ICS format for events. Thanks for this library, we really appreciate the time it saved us!

We would like to include a full address for an event in the ICS file, such as:

> Venue Name, 180 Example Street, Suburb, STATE, 1234

I believe this should be possible based on the example ICS located here: https://icalendar.org/

Specifically:

`LOCATION:Hodgenville\, Kentucky`

It seems based on the examples on that page that commas are allowed, but must be escaped. So I believe this can be fixed just by updating this line in ics.php:

`            $url[] = 'LOCATION:'.str_replace(',', '', $link->address);`

I'll try to prepare a pull request for this change!

**Comment by aethr** [comment]
#37 pull request with a very simple fix to address this issue.

**Comment by lptn** [comment]
fixed
