### ISSUE TITLE
[QUESTION] Is it possible to add guests?

### ISSUE THREAD

**Issue by kborge** [spatie/calendar-links#41]
So I'm wondering how to add guest? I tried adding parameters emails and guests but no luck.
Do you have any documentation about the google calendar parameters?

**Comment by kborge** [comment]
Found the answer: https://stackoverflow.com/questions/22757908/google-calendar-render-action-template-parameter-documentation

**Comment by lptn** [comment]
@kborge 
It's not possible in current version, but feel free to create a PR to support this feature:
```php
$link->google(['guests' => 'kborge@example.com'])
```
