### ISSUE TITLE
Minimal PHP version

### ISSUE THREAD

**Issue by Dacesilian** [spatie/calendar-links#42]
Hello, is PHP 7.0 really needed or can I use library with older PHP? I have a project with PHP 5.6 and composer won't let me to install spatie/calendar-links.

**Comment by Eyalevin** [comment]
Hey 	Dacesilian,
Now at the project uses 7.0 and all tests work at 7.0 ^
If you want running at the lowest version like 5.6 you need to make some changes at the code.
I think at pull requests you can find pull requests for lowest PHP 

BR,
Eyal Levin

**Comment by Dacesilian** [comment]
These are small changes and it would be nice to support older PHP. Anyway thank you for your fast reply.

https://github.com/spatie/calendar-links/pull/7
