### ISSUE TITLE
`$this->from`  is not a valid \DateTime object

### ISSUE THREAD

**Issue by emulienfou** [spatie/calendar-links#43]
Hello there, following some recent changes made, there is in the next line a new introduced issue.
https://github.com/spatie/calendar-links/blob/c141d1b544b20cb36ec93aafaed5b1d6e1da5163/src/Generators/Yahoo.php#L15

In the `Link::__constructor` the next code is used and set an already formatted dateTime:
https://github.com/spatie/calendar-links/blob/53f14ce66dfb68bb0b4438a604132553d639db8b/src/Link.php#L47

**Comment by lptn** [comment]
Fixed within v1.2.0
