### ISSUE TITLE
Ics link doesn't work on email

### ISSUE THREAD

**Issue by fuscage** [spatie/calendar-links#44]
Hello the team,

The link ics, doesn't work on email, only on a html page...

I have send to gmail and outlookweb and the ics link is filtered by the mailbox... 

I see in the "original" source this : 
`<a href="data:text/calendar;charset=utf8,%0ABEGIN:VCALENDAR%0AVERSION:2.0%0ABEGIN:VEVENT%0ADTSTART:20181030T133000%0ADTEND:20181030T143000%0ASUMMARY:titre%0ADESCRIPTION:description%0ALOCATION:rue%0AEND:VEVENT%0AEND:VCALENDAR">ICS<a/>`

but in the "final" source this : 
`<a>ICS</a>`

Can you fixed that? Why is filtered in the final source?

Thanks

**Comment by lptn** [comment]
@fuscage 
I only can guess that email clients filter our such links for security reasons. You can bypass it by sending ics file as attachment:
![image](https://user-images.githubusercontent.com/5278175/51074948-3dd84580-1696-11e9-953f-dbefb1d1e386.png)


Feel free to open PR if you know how to solve this issue directly without bypassing.

**Comment by lptn** [comment]
@fuscage 
I found this approach on eventbrite.com emails:
```html
// add to google
https://www.eventbrite.com/calendar.ics?utm_campaign=order_confirm&utm_medium=email&ref=eemailordconf&eid=54279023019&utm_source=eb_email&calendar=google
// add to outlook
https://www.eventbrite.com/calendar.ics?utm_campaign=order_confirm&utm_medium=email&ref=eemailordconf&eid=54279023019&utm_source=eb_email&calendar=outlook
// add to iCal
https://www.eventbrite.com/calendar.ics?utm_campaign=order_confirm&utm_medium=email&ref=eemailordconf&eid=54279023019&utm_source=eb_email&calendar=ical
// add to yahoo
https://www.eventbrite.com/calendar.ics?utm_campaign=order_confirm&utm_medium=email&ref=eemailordconf&eid=54279023019&utm_source=eb_email&calendar=yahoo
```

and then add a redirection to a proper URL (based on `calendar` query param) that can be generated by `spatie/calendar-links` package 👍

**Comment by lptn** [comment]
@sebastiandedeyne
what do you think, should we update package docs to cover this case for emails or this is something our of scope?

Another similar possibly out of scope of this lib problem: should we shrink description text, bc of [length limitations of GET query](https://stackoverflow.com/questions/2659952/maximum-length-of-http-get-request)?

**Comment by sebastiandedeyne** [comment]
Sounds good to add that to the docs!

But I'd hold off on the GET limitations for now.

**Comment by kylemilloy** [comment]
I built a package that specifically handles ics v2 packages for this purpose.

https://github.com/itsnubix/nowcal/

In Laravel you'd look at doing something like:

```php
use NowCal\NowCal;
// other imports

class MyEmail extends Mailable {
        protected $props;

        public function __construct($props)
        {
                $this->props = $props;
        }

        public function build() 
        {
                return $this->view('my.view')
                        // This is where you attach the .ics file
                        ->attach(NowCal::file($this->props), [
                                'as' => 'invite-name.ics',
                                'mime' => 'text/calendar'
                        ])
        }
}

class MyController extends Controller {
    public function sendMail(Request $request) {
        $invite_props = [
                'start' => 'now + 1 hour'
        ];

        Mail::to('example@email.com')
                ->send(new MyEmail($invite_props));
    }    
}
```

At a minimum you just need to include a start time that can be parsed by php's DateTime class.
