### ISSUE TITLE
Cover by docs a case how to send "add event links" via email

### ISSUE THREAD

**Issue by lptn** [spatie/calendar-links#50]
Ref: https://github.com/spatie/calendar-links/issues/44#issuecomment-455533351

**Comment by orphanedrecord** [comment]
I am curious to see your approach, as I have a use case for this myself, especially handling ics data.

**Comment by lptn** [comment]
@orphanedrecord

I know 2 options:
 1. use only google, yahoo and outlooks links + attach .ics as file
 1. use links to YOUR domain that will return [redirect] response you need 

Could you please share your approach?

**Comment by orphanedrecord** [comment]
Those are the methods that come to mind for me as well.

I was leaning toward option two, as this could allow changes to the event ics data after an email is sent (which should be rare). For example, if we discovered a typo or clarified something in the description, we could not fix this for an attachment that has already been sent!

Plus the idea of not including an email attachment just feels cleaner. We could include a nice CTA button link in the email to download the .ics by hitting a script on our website. My inclination is the latter may have a higher conversation rate.

Thank you for your work on this project!

**Comment by ziming** [comment]
Hi could anyone share some source code examples?
