### ISSUE TITLE
Feature Request: Support adding attendee via ATTENDEE property

### ISSUE THREAD

**Issue by freakpants** [spatie/calendar-links#54]
This is a feature that works for ics at least, and adds an email address so you can invite attendees in outlook. I don't know if it works for other formats/clients. Simplest Implementation would take a string, more advanced one would take an array, and even properties like required participant, or delegation.

https://www.kanzaki.com/docs/ical/attendee.html

**Comment by Bwanophele** [comment]
I needed it so I overrode Link.php
```
/**
	 * @param array $attendee
	 *
	 * @return $this
	 */
	public function attendee(array $attendee)
	{
		$this->attendee = $attendee;
		return $this;
	}

	/**
	 * @param string $organizer
	 *
	 * @return $this
	 */
	public function organizer(string $organizer)
	{
		$this->organizer = $organizer;
		return $this;
	}
```
and Ics.php :

line 18 : 
`'METHOD:REQUEST',`

line 37 : 
```
if ($link->organizer) {
			$url[] = 'ORGANIZER:' . $this->escapeString($link->organizer) . ':mailto:' . $this->escapeString($link->organizer);
			$url[] = 'ATTENDEE;CUTYPE=INDIVIDUAL;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;RSVP=
 TRUE;CN=' . $this->escapeString($link->organizer) . ';X-NUM-GUESTS=0:mailto:' . $this->escapeString($link->organizer);
		}

		if ($link->attendee) {

			foreach ($link->attendee as $attendee) {
				$url[] = 'ATTENDEE;CUTYPE=INDIVIDUAL;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;RSVP=
 TRUE;CN=' . $this->escapeString($attendee) . ';X-NUM-GUESTS=0:mailto:' . $this->escapeString($attendee);
			}
		}
```

I'm not allowed to make a PR, and this works like a charm in my project :)

**Comment by freakpants** [comment]
I did something similar in a fork:
https://github.com/webkinder/calendar-links/commit/991c26cbd5064b178d79db0884bc44ddd0655f1d

But I'd love to be able to return to the original branch for update reasons. I dont know if our implementation would affect other things, especially other formats/clients.

**Comment by atymic** [comment]
@freakpants 

I'd consider opening a PR so `spatie` can check :)

**Comment by lptn** [comment]
@freakpants
@atymic

thanks guys. In order to add a feature to Link class, we need to support it at least by 2 generators. Feel free to implement and create a PR. Here I explained it in details: https://github.com/spatie/calendar-links/pull/67#pullrequestreview-402580423
