### ISSUE TITLE
Google calendar end date is before start date when allDay = true

### ISSUE THREAD

**Issue by antanova** [spatie/calendar-links#56]
I fixed this temporarily in the Google Generator by adding a day to `$link->to` like this:
 
```php
if ($link->allDay) {
    $link->to->add(new \DateInterval('P1D'));
}
```

**Comment by lptn** [comment]
@antanova 
Do you use the last version of the package?

Could you please provide some input/output examples so I can easily reproduce it and probably create a fix?

**Comment by antanova** [comment]
Apologies for the delay. I'm using version 1.2.3. Here's an example that reproduces my issue:

```php
$allDay = true;
$date = new DateTime();
$date->setTimeZone(new DateTimeZone('Europe/London'));
$dateEnd = clone $date;
$dateEnd->add(new DateInterval('P1D')); // issue persists when I add 2 days or don't add anything.

use Spatie\CalendarLinks\Link;
$link = $link = new Link( 'Example title', $date, $dateEnd, $allDay);

?>
<a href="<?php echo $link->google(); ?>">Click here</a>
```

If I follow the generated link, then the *start date* in Google is today, and the *end date* is yesterday.

![Screenshot_2019-05-02 Google Calendar - Event details](https://user-images.githubusercontent.com/2981476/57077186-4c994580-6ce3-11e9-98fd-0dfcc64ad41b.png)

**Comment by lptn** [comment]
Hey @antanova 
Thanks for your great report! I've made some fixes and will be happy if you check them out, the branch is `60-fix-allday-links`
