### ISSUE TITLE
ical did not show button RSVP in gmail ( laravel )

### ISSUE THREAD

**Issue by dennyaris** [spatie/calendar-links#59]
How to show button yes, no or maybe in invatation gmail and this invitation automatically link to google calendar? 

<img width="1040" alt="Screen Shot 2019-05-14 at 10 15 01" src="https://user-images.githubusercontent.com/20966148/57668365-484d2080-7631-11e9-9393-1685501e4a81.png">

here my code :
<img width="720" alt="Screen Shot 2019-05-14 at 10 11 28" src="https://user-images.githubusercontent.com/20966148/57668403-63b82b80-7631-11e9-84f8-3a7f844d7e33.png">

**Comment by lptn** [comment]
@dennyaris 
It's a bit of the scope of this repo, but you can try to use microdata formats: https://developers.google.com/gmail/markup/reference/rsvp-action

Please update this issue (and reopen) if you find any other solutions to add RSVP. Thanks!
