### ISSUE TITLE
Ideas for v2

### ISSUE THREAD

**Issue by lptn** [spatie/calendar-links#63]
This package uses semver 2.0, that means we can't ship BC changes without bumping the major version. Here we can collect wishes to implement within version 2.0 of the package

**Comment by lptn** [comment]
Use `DateTimeInterface` to support `DateTimeImmutable`

**Comment by lptn** [comment]
Use stricter validation for all-day events: `from` and `to` dates should start from midnight and anAPIs to create a $link instance with invalid dates should not exist

**Comment by lptn** [comment]
Idea: Allow to use custom generators/formatters

**Comment by aiancuevc** [comment]
Allow settings appointment reminder

**Comment by lptn** [comment]
@aiancuevc 
Good idea. Could you please help me to make a research on which services supports it?

**Comment by aiancuevc** [comment]
@lptn certainly, was planning to do a PR on this as i need it for my current project (doctor appointment email reminder + cal invite). VALARM is what I recall reading about last week on this: https://tools.ietf.org/id/draft-daboo-valarm-extensions-04.html

**Comment by ankurk91** [comment]
Add `RRULE` property if it is allowed in links.

https://icalendar.org/iCalendar-RFC-5545/3-8-5-3-recurrence-rule.html

**Comment by lptn** [comment]
All major ideas are implemented within 1.X version. It's currently possible to use custom Generators, that means package users (developers) can add missing features directly in their projects, like:
 - RRULE property if it is allowed in links.
 - VALARM

for the ics generator we have a lot of feature requests, but 98% of these features not supported by other generators/platforms/calendars. Most likely we'll not add these features to this package
