### ISSUE TITLE
Disabling guest from modifying the dates

### ISSUE THREAD

**Issue by Bwanophele** [spatie/calendar-links#65]
When I create the google link via the module and then click on it in the mail, I get on the event registration in Google.
The problem is that I can modify the dates and time in this preview before submitting. 
How can I can disable the modification of dates/times and title ?

**Comment by lptn** [comment]
@Bwanophele 
There is no option to add an event without edit mode (or at least I don't know it and there is no information about it in opec sources). If you find it, feel free to create a PR to this repo or at least this unofficial docs repo: https://github.com/InteractionDesignFoundation/add-event-to-calendar-docs/blob/master/services/google.md
