### ISSUE TITLE
How can I install without the 'composer' stuff?

### ISSUE THREAD

**Issue by pkiula** [spatie/calendar-links#66]
Is it possible to install it just as a `class`, with `include`? I'd like to avoid the whole composer jazz and just it simple in a functional programming way. Many thanks!

**Comment by atymic** [comment]
In my opinion that's not a good approach. It would make it very hard to update in the future as well.

I don't think the package will offer loading outside of composer.

**Comment by lptn** [comment]
@pkiula
This package created to work with composer. The only way to use it without composer: use a modified version of this package (fork it or just copy-paste and modify)
