### ISSUE TITLE
Can we add Z with start and end date time in Google Calendar so that when adding events to Google calendar it picks up the user's local time

### ISSUE THREAD

**Issue by samirchauhan** [spatie/calendar-links#69]
Something like this 
$url .= '&dates='.$link->from->format($dateTimeFormat).'Z/'.$link->to->format($dateTimeFormat).'Z';

**Comment by samirchauhan** [comment]
@lptn

**Comment by lptn** [comment]
@samirchauhan 
`Z` means UTC tz, not the local tz. If you need to use a local tz, you need to omit `ctz` query param and `Z` suffix for both dates. We can't use it, bc we'll loose a control over time then. 

In next major version I think we'll add an ability to use custom generators so you can extend `\Spatie\CalendarLinks\Generators\Google` and change this logic
