### ISSUE TITLE
ICS download link does not work on Microsoft browser (including edge)

### ISSUE THREAD

**Issue by dogawaf** [spatie/calendar-links#71]
The ICS download link proposed by this library does not work on Microsoft browsers because they do not support navigating to data uri: 

> For security reasons, data URIs are restricted to downloaded resources. Data URIs cannot be used for navigation, for scripting, or to populate frame or iframe elements.
source: https://docs.microsoft.com/en-us/previous-versions//cc848897(v=vs.85)

**Comment by lptn** [comment]
@dogawaf 
There is nothing to do within this lib. But you can bypass it: redirect user to a route to download a file instead

**Comment by dogawaf** [comment]
I would not ask you to fix IE limitations :)

But at least the limitation should be documented here.

More insights:
- The issue on edge tracker: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/4282810/
- Blog article from a Microsoft dev: https://textslashplain.com/2018/08/06/script-generated-download-files/
- Test page: https://bayden.com/test/data.htm

There is also this JS library that may help: http://danml.com/download.html

**Comment by lptn** [comment]
done: added to the bottom of the Usage section: https://github.com/spatie/calendar-links#usage

**Comment by robbygeybels** [comment]
Does it work on the chromium based Edge browsers?

**Comment by wxactly** [comment]
Use [download.js version 1.4.8](https://github.com/rndme/download/releases/tag/v1.4.8) to trigger ics file download in the browser - it works in Internet Explorer!

PHP:
```php
$link = Link::create('My Event', $from, $to);
echo '<a href="' . $link->ics() . '" class="ics-link">Download My Event</a>';
```

jQuery:
```js
$('.ics-link').click(function (event) {
  var href = $(this).attr('href');
  download(href, 'download.ics');
  event.preventDefault();
});
```

Full docs: https://github.com/rndme/download

**Comment by lptn** [comment]
Hey @wxactly

Let me improve (a bit) your solution and rely on [`download` attribute](https://developer.mozilla.org/en-US/docs/Web/API/HTMLAnchorElement/download) instead:

```php
$link = Link::create('My Event', $from, $to);
echo '<a href="' . $link->ics() . '" class="ics-link" download="event.ics">Download My Event</a>';
```

```js
$('a[download]').click(function (event) {
  var href = $(this).attr('href');
  var storeAsFilename = $(this).attr('download') || 'event.ics';
  download(href, storeAsFilename);
  event.preventDefault();
});
```

PS: you can

**Comment by AnkitgargAI** [comment]
I want to create icalender url for apple mail account. please help
