### ISSUE TITLE
UTC forcing in WebOutlook

### ISSUE THREAD

**Issue by HamHamFonFon** [spatie/calendar-links#77]
Hello, 
I have a question, why on class WebOutlook, the DatetimeZone is forced to UTC but in Google the Datetimezone is from dates send from object Link ? It's better in Google class :), so could you change it in WebOutlook class ?
Thank you.

**Comment by lptn** [comment]
@HamHamFonFon 
I don't know how to specify tz manually for outlook, this is only one reason. I also prefer to use GoogleGenerator-like approach, but it's not always possible. If you know how to implement WebOutlook in the same fashion  - please create a PR or at least share info Thanks!
