### ISSUE TITLE
Creating ICS Link

### ISSUE THREAD

**Issue by vik0803** [spatie/calendar-links#8]
Hello All,

I am trying to create a $link->ics() where is it is creating the data and I am trying to add the content to file via mail->attach data but it doesn't get recognised. Seems to be something wrong so appreciate your help.

Thank,
Vik

**Comment by aayush-mittal** [comment]
@vik0803, I had also faced same issue. So I fixed this issue and created pull request for that. 
Currently i fixed issue like this.

if($string['calType'] == "ics") {
          // Generate a data uri for an ics file (for iCal & Outlook)
//          $redirectLink = $link->ics();
          header('Content-Type: text/calendar; charset=utf-8');
          header('Content-Disposition: attachment; filename="event.ics"');
          $icsData = array ('BEGIN:VCALENDAR', 'VERSION:2.0', 'BEGIN:VEVENT', 'URL:https://'. $_SERVER['SERVER_NAME'], 'DTSTART:'.$link->from->format('Ymd\THis'), 'DTEND:'.$link->to->format('Ymd\THis'), 'SUMMARY:'.$link->title);
          $redirectLink = join("\n",$icsData);
          echo ($redirectLink);
          exit();
        }

**Comment by sebastiandedeyne** [comment]
PR is merged, feel free to reopen if this is still an issue!
