### ISSUE TITLE
Type hints not accepted by php 7.0

### ISSUE THREAD

**Issue by kmccurley** [spatie/calendar-links#87]
I had trouble using the library because it rejects type hints for scalar types. For example, in Link.php you have:
bool $allDay = false
int $numberofDays =1
The documentation of php type hints is a mess, but basically this doesn't work on PHP 7.0. The specific error I see is:
```
PHP Fatal error:  Default value for parameters with a class type hint can only be NULL in vendor/spatie/calendar-links/src/Link.php on line 40

**Comment by lptn** [comment]
@kmccurley 
what is your package version and php version?
Note, latest package version requires PHP7.2+ https://github.com/spatie/calendar-links/blob/master/composer.json#L19 and soon we'll switch to PHP7.3+

Reasons you can find here: https://github.com/spatie/calendar-links/issues/84

**Comment by kmccurley** [comment]
I'm running on ubuntu 18.04LTS.

When I checked this out with `composer require spatie/calendar-links` just today, it pulled in
```{
    "require": {
        "spatie/calendar-links": "^1.3"
    }
}
```
This only requires PHP 7.0. Since you have already moved on to later versions of PHP, I'll look for another solution.

**Comment by lptn** [comment]
@kmccurley 
I checked travis CI logs, v1.3. should work on php7.0: https://travis-ci.org/github/spatie/calendar-links/jobs/680972891

Most likely the problem lies on your end, probably it's not imported Link class, just try to run `composer update` and ensure that all classes are imported
