### ISSUE TITLE
ics not working, because of timezone format

### ISSUE THREAD

**Issue by ligne13** [spatie/calendar-links#88]
Hi,
the ics data returned contains the lines below for the start and end dates:
```
DTSTART;TZID=+00:00:20200528T193000
DTEND;TZID=+00:00:20200528T203000
```
The import in my Apple Calendar app does not work.
If I manually change the TZ in the ics file as below, it works:
```
DTSTART;TZID=Europe/Paris:20200528T193000
DTEND;TZID=Europe/Paris:20200528T203000
```

Is there a way to specify the Timezone ? 
If not, is this a bug ?

**Comment by lptn** [comment]
duplicate of #73
