### ISSUE TITLE
ics file using wrong timezone.

### ISSUE THREAD

**Issue by blorange2** [spatie/calendar-links#89]
Hi,

As all applications we've ever created have been in, and for UK residents, our default timezone is `Europe\London`, in one such application we allow users to add events to their calendar via either Google Calendar or an ics file for Office 365.

The time we're using for example is 10:00 - 11:30 GMT

The Google Calendar link outputs this time however, the ics file sets the time as 11:00 to 12:30, I might be just being stupid but is there an obvious reason this would be the case?

Here is the output of the .ics file 

```

BEGIN:VCALENDAR
VERSION:2.0
BEGIN:VEVENT
UID:968ac38f164dcc94d1c3d7a1c7849288
SUMMARY:Tax Relief & Support for Small Businesses - SME COVID-19 Series
DTSTART;TZID=Europe/London:20200519T100000
DTEND;TZID=Europe/London:20200519T113000
DESCRIPTION:Tax Relief & Support for Small Businesses - SME COVID-19 Series
LOCATION:Webinar
END:VEVENT
END:VCALENDAR

```

This looks correct?

**Comment by lptn** [comment]
duplicate #88
