### ISSUE TITLE
Undefined class constant 'ATOM'

### ISSUE THREAD

**Issue by rahul05ranjan** [spatie/calendar-links#90]
```php
    /** @see https://tools.ietf.org/html/rfc5545#section-3.8.4.7 */
    protected function generateEventUid(Link $link): string
    {
        return md5($link->from->format(\DateTimeInterface::ATOM).$link->to->format(\DateTimeInterface::ATOM).$link->title.$link->address);
    }
```

**Comment by lptn** [comment]
@rahul05ranjan 
what's your PHP version number? Package number

**Comment by rahul05ranjan** [comment]
My php version PHP `7.3.19 ` and package version no `^1.2`

**Comment by lptn** [comment]
@rahul05ranjan 
>package version no ^1.2

this is not a version, this a version RANGE from 1.2.0 to 1.2.4

We started to use \DateTimeInterface::ATOM in v1.4.0 that has a req. PHP 7.2+
![image](https://user-images.githubusercontent.com/5278175/85105986-18992080-b214-11ea-8a09-29bafc91a6e0.png)

If you think it's a bug in our package, feel free to create a PR with a new test that will fail on specific versions of the package and PHP

**Comment by kitro** [comment]
@rahul05ranjan  I have the same error, I rollback to version `1.3.0` of calendar-links and it's worked.
My php version is `PHP 7.2.26`  and I get the same error `Undefined class constant ATOM`

**Comment by lptn** [comment]
I just checked this const on different versions: 
![image](https://user-images.githubusercontent.com/5278175/85390286-48686100-b551-11ea-8d29-d4c6756f43c3.png)

and couldn't find a error. Fill free to create a failing test if you sure about this bug and your PHP version (please use phpinfo to check your version, `php -v` returns a php-cli version)

**Comment by lptn** [comment]
closing as inactive
