### ISSUE TITLE
Minor: syntax error in the example written in README.md

### ISSUE THREAD

**Issue by rasik-source** [spatie/calendar-links#92]
syntax error, unexpected ')' inside readme:

Link::create(
    'Birthday',
    DateTime::createFromFormat('Y-m-d H:i', '2018-02-01 09:00'),
    DateTime::createFromFormat('Y-m-d H:i', '2018-02-01 18:00')**)**
)->google();

**Comment by lptn** [comment]
thanks a lot! Fixed
