### ISSUE TITLE
Cleanup of Description for ICS

### ISSUE THREAD

**Issue by ednailor** [spatie/calendar-links#97]
When passing any HTML code to the description, Apple and Outlook will often display the HTML code as text, making for a very unreadable set up for the user.

To get around this, I have had to do a lot of find and replace with the description and send it back through the script for almost each generated item.

For this to be truly robust, there should be something that filters the content for the description to help clean that up, replacing items like `<p>` with `\n` to help ensure a clean appearance for the user.

Additionally, the same HTML information can be passed through as an X-ALT-DESC variable for MS so that Outlook can use that without needing to be filtered. By wrapping the HTML content within the following, the HTML passes through nice and clean (although some inline styles may still need to be addressed beforehand.):

`X-ALT-DESC;FMTTYPE=text/html:<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN"><HTML><HEAD><TITLE></TITLE></HEAD><BODY>`**DESCRIPTION HTML**`</BODY></HTML>`

Not sure if this would be considered a bug or enhancement, but worth sharing for others as well.

**Comment by lptn** [comment]
IMO this feature should not be handled by this package, closing.
